name: Deploy yoshikawa-staging

on:
  push:
    branches:
      - devalop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /ryoto-hiji.com/public_html/yoshikawa-staging.ryoto-hiji.com/wp-content/themes/yoshikawa-hospital/
